version: '2'

volumes:
  jenkins_home:
    external: true

services:
  app-runtime:
    build: 
      context: ../
      dockerfile: docker/dockerfile
    ports:
     - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "gitlab.localdomain:10.10.40.102"
      - "registry.localdomain:10.10.40.102"
      - "repo.localdomain:10.10.40.102"